package enginesql

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"reflect"
	"strings"

	"github.com/amberpixels/r3"
)

var _ r3.Upserter[any, any] = &BaseCRUD[any, any]{}

// Upsert inserts entity, or updates the colliding row when it conflicts on the
// conflict target (the primary key by default). It is the reference SQL upsert
// for the raw drivers, emitting flavor-appropriate SQL through [Flavor.UpsertClause]
// (Postgres/SQLite ON CONFLICT ... DO UPDATE, MySQL ON DUPLICATE KEY UPDATE).
//
// The insert branch obeys Creatable and stamps created_at/updated_at; the
// on-conflict update branch obeys Mutable (a restricted UpdateOnConflict set is
// rejected exactly like Patch when it names a non-mutable column) and bumps
// updated_at. The write guard bypass (r3.WithoutWriteGuard) skips the capability
// check the same way Create/Patch do. The stored row is returned via RETURNING
// where supported, and re-fetched by the conflict target otherwise.
func (r *BaseCRUD[T, ID]) Upsert(ctx context.Context, entity T, opts ...r3.UpsertOption) (T, error) {
	spec := r3.NewUpsertSpec(opts...)

	conflictCols := spec.ConflictColumns
	if len(conflictCols) == 0 {
		conflictCols = []string{r.Meta.PKColumn}
	}

	updateCols, err := r.upsertUpdateColumns(ctx, &entity, spec)
	if err != nil {
		return entity, err
	}
	insertCols := r.upsertInsertColumns(ctx, &entity)
	vals := r.Meta.FieldValuesForColumns(entity, insertCols)

	base := fmt.Sprintf(
		"INSERT INTO %s (%s) VALUES (%s) %s",
		r.Meta.TableName,
		ColumnsString(insertCols),
		r.Flavor.Placeholders(len(insertCols), 1),
		r.Flavor.UpsertClause(conflictCols, updateCols),
	)

	// RETURNING gives the stored row directly, but only when a DO UPDATE runs on
	// conflict — DO NOTHING returns no row on a collision, so fall through to the
	// re-fetch path for it (and for MySQL, which lacks RETURNING entirely).
	if r.Flavor.SupportsRETURNING && len(updateCols) > 0 {
		query := base + " RETURNING " + ColumnsString(r.Meta.Columns)
		dests := r.Meta.ScanDest(&entity)
		if err := r.Executor.QueryRowContext(ctx, query, vals...).Scan(dests...); err != nil {
			return entity, err
		}
		return entity, nil
	}

	if _, err := r.Executor.ExecContext(ctx, base, vals...); err != nil {
		return entity, err
	}
	return r.fetchByColumns(ctx, conflictCols, r.Meta.FieldValuesForColumns(entity, conflictCols))
}

// upsertInsertColumns returns the columns an upsert's INSERT branch writes: the
// Creatable columns plus managed created_at/updated_at (via createColumns), and
// a caller-supplied primary key. A non-zero PK is included so an upsert keyed by
// a non-generated PK (e.g. a string settings key) inserts under that key; a zero
// PK is left out so a serial/auto-increment PK is still generated by the DB.
func (r *BaseCRUD[T, ID]) upsertInsertColumns(ctx context.Context, entityPtr *T) []string {
	cols := r.createColumns(ctx, entityPtr)
	if pk := r.Meta.PKValue(*entityPtr); pk != nil && !reflect.ValueOf(pk).IsZero() {
		return append([]string{r.Meta.PKColumn}, cols...)
	}
	return cols
}

// upsertUpdateColumns returns the columns the on-conflict update branch writes.
// With no UpdateOnConflict option it is every mutable column plus managed
// updated_at (a full replace). With an explicit set it mirrors Patch: reject the
// PK/soft-delete/unknown columns (ValidatePatchColumns) and non-mutable columns
// (RequireMutableColumns), then append managed updated_at.
func (r *BaseCRUD[T, ID]) upsertUpdateColumns(
	ctx context.Context, entityPtr *T, spec r3.UpsertSpec,
) ([]string, error) {
	if len(spec.UpdateFields) == 0 {
		return r.updateColumns(ctx, entityPtr), nil
	}
	cols := FieldsToColumns(spec.UpdateFields)
	cols, err := r.Meta.ValidatePatchColumns(cols)
	if err != nil {
		return nil, err
	}
	if err := RequireMutableColumns(ctx, r.Schema, cols); err != nil {
		return nil, err
	}
	cols = append(cols, r.stampManagedTimestamps(ctx, entityPtr, cols, r3.WriteOpMutate)...)
	return cols, nil
}

// fetchByColumns selects the single row matching cols = vals and scans it into a
// fresh entity, normalizing "no rows" to r3.ErrNotFound. It is the upsert
// re-fetch for backends without a usable RETURNING (MySQL, or the DO NOTHING
// branch).
func (r *BaseCRUD[T, ID]) fetchByColumns(ctx context.Context, cols []string, vals []any) (T, error) {
	var entity T
	whereParts := make([]string, len(cols))
	for i, c := range cols {
		whereParts[i] = r.Flavor.WhereEq(c, i+1)
	}
	query := fmt.Sprintf(
		"SELECT %s FROM %s WHERE %s",
		ColumnsString(r.Meta.Columns),
		r.Meta.TableName,
		strings.Join(whereParts, " AND "),
	)
	dests := r.Meta.ScanDest(&entity)
	err := r.Executor.QueryRowContext(ctx, query, vals...).Scan(dests...)
	if errors.Is(err, sql.ErrNoRows) {
		return entity, r3.ErrNotFound
	}
	return entity, err
}
