# justfile — generated by justx · the justfile companion
# https://github.com/amberpixels/just-x
#
# Blocks between `# >>> justx:<id>` and `# <<< justx:<id>` are managed by justx.
# Edit anything outside the fences freely; `j @upgrade` (v2) re-syncs managed blocks.

# standardgo carries the ruleset and the golangci-lint engine in one binary, so this
# repo holds no lint config of its own. It is run via `go run`, not a go.mod tool
# directive, to keep it out of this library's dependency graph.
# The fmt/lint/fix fences are removed for the same reason - they must not resync.
standardgo := "github.com/amberpixels/standardgo/cmd/standardgo@v0.2.1"

# The floor this library promises to support. Keep in sync with the `go` directive
# in go.mod - that is the number consumers actually see. CI passes FLOOR_GO=local,
# having already installed the floor toolchain, so it never downloads a second one.
floor_go := env("FLOOR_GO", "go1.26.0")

# Default recipe: format (rewrites, decides nothing; `just fix` is the mutable one)
default: fmt

# format Go code - rewrites to canonical form
fmt:
    go run {{ standardgo }} fmt ./...

# lint Go code - reports findings, changes nothing
lint:
    go run {{ standardgo }} ./...

# auto-fix what can be fixed - run on a clean tree and read the diff
fix:
    go run {{ standardgo }} ./... --fix

# >>> justx:test (managed) — `j @upgrade` re-syncs; remove these fences to take over
# run tests
test:
    go test ./...
# <<< justx:test

# check that the go.mod floor still builds and vets. vet compiles the tests too,
# so this covers the test dependencies at the floor without needing Docker.
floor:
    GOWORK=off GOTOOLCHAIN={{ floor_go }} go build ./...
    GOWORK=off GOTOOLCHAIN={{ floor_go }} go vet ./...

# >>> justx:build (managed) — `j @upgrade` re-syncs; remove these fences to take over
# build
build:
    go build ./...
# <<< justx:build

# run all checks - read-only, safe for CI
ci: lint test floor

# Integration tests for CI: serialize packages with `-p 1` so the
# testcontainers-backed suites (pq/pgx/mysql/gorm/bun/gopg + the petstore
# Postgres) don't all spin up DB containers at once and exhaust the runner —
# the source of intermittent "failed to connect" flakes. Slower but deterministic.
test-integration:
    go test -p 1 ./...

# Test only short tests (skip integration tests requiring Docker)
test-short:
    go test -short ./...

# Run the pet store example (starts PostgreSQL in Docker + the Go server)
example:
    docker start petstore-pg 2>/dev/null || \
        docker run -d --name petstore-pg -p 5432:5432 \
            -e POSTGRES_USER=petstore -e POSTGRES_PASSWORD=petstore -e POSTGRES_DB=petstore \
            postgres:18-alpine
    @echo "Waiting for PostgreSQL..."
    @until docker exec petstore-pg pg_isready -U petstore -q 2>/dev/null; do sleep 0.2; done
    go run ./examples/02petstore/cmd
