# justfile — generated by justx · the justfile companion
# https://github.com/amberpixels/just-x
#
# Blocks between `# >>> justx:<id>` and `# <<< justx:<id>` are managed by justx.
# Edit anything outside the fences freely; `j @upgrade` (v2) re-syncs managed blocks.

# Default recipe: format (rewrites, decides nothing; `just fix` is the mutable one)
default: fmt

# >>> justx:fmt (managed) — `j @upgrade` re-syncs; remove these fences to take over
# format Go code - rewrites to canonical form
fmt:
    go tool standardgo fmt ./...
# <<< justx:fmt

# >>> justx:lint (managed) — `j @upgrade` re-syncs; remove these fences to take over
# lint Go code - reports findings, changes nothing
lint:
    go tool standardgo ./...
# <<< justx:lint

# >>> justx:fix (managed) — `j @upgrade` re-syncs; remove these fences to take over
# auto-fix what can be fixed - run on a clean tree and read the diff
fix:
    go tool standardgo ./... --fix
# <<< justx:fix

# >>> justx:test (managed) — `j @upgrade` re-syncs; remove these fences to take over
# run tests
test:
    go test ./...
# <<< justx:test

# >>> justx:build (managed) — `j @upgrade` re-syncs; remove these fences to take over
# build
build:
    go build ./...
# <<< justx:build

# >>> justx:ci (managed) — `j @upgrade` re-syncs; remove these fences to take over
# run all checks - read-only, safe for CI
ci: lint test
# <<< justx:ci

# Integration tests for CI: serialize packages with `-p 1` so the
# testcontainers-backed suites (pq/pgx/mysql/gorm/bun/gopg + the petstore
# Postgres) don't all spin up DB containers at once and exhaust the runner —
# the source of intermittent "failed to connect" flakes. Slower but deterministic.
test-integration:
    go test -p 1 ./...

# Test only short tests (skip integration tests requiring Docker)
test-short:
    go test -short ./...

# Run the pet store example (starts PostgreSQL in Docker + the Go server)
example:
    docker start petstore-pg 2>/dev/null || \
        docker run -d --name petstore-pg -p 5432:5432 \
            -e POSTGRES_USER=petstore -e POSTGRES_PASSWORD=petstore -e POSTGRES_DB=petstore \
            postgres:18-alpine
    @echo "Waiting for PostgreSQL..."
    @until docker exec petstore-pg pg_isready -U petstore -q 2>/dev/null; do sleep 0.2; done
    go run ./examples/02petstore/cmd
